# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orbe_speech.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orbe_speech.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11orbe_speech.proto\x12\norbespeech\"M\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x12\x0c\n\x04last\x18\x04 \x01(\x08\"Y\n\x11TranscribeRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x13\n\x0bsample_rate\x18\x04 \x01(\x05\"=\n\x12TranscribeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x19\n\x11language_detected\x18\x02 \x01(\t\"L\n\x0fTranscriptEvent\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x19\n\x11language_detected\x18\x03 \x01(\t\"\x7f\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x10\n\x08provider\x18\x03 \x01(\t\x12\x10\n\x08voice_id\x18\x04 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x05 \x01(\t\x12\x15\n\routput_format\x18\x06 \x01(\t2\xf6\x01\n\rSpeechService\x12K\n\nTranscribe\x12\x1d.orbespeech.TranscribeRequest\x1a\x1e.orbespeech.TranscribeResponse\x12K\n\x10TranscribeStream\x12\x16.orbespeech.AudioChunk\x1a\x1b.orbespeech.TranscriptEvent(\x01\x30\x01\x12K\n\x10SynthesizeStream\x12\x1d.orbespeech.SynthesizeRequest\x1a\x16.orbespeech.AudioChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orbe_speech_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=33
  _globals['_AUDIOCHUNK']._serialized_end=110
  _globals['_TRANSCRIBEREQUEST']._serialized_start=112
  _globals['_TRANSCRIBEREQUEST']._serialized_end=201
  _globals['_TRANSCRIBERESPONSE']._serialized_start=203
  _globals['_TRANSCRIBERESPONSE']._serialized_end=264
  _globals['_TRANSCRIPTEVENT']._serialized_start=266
  _globals['_TRANSCRIPTEVENT']._serialized_end=342
  _globals['_SYNTHESIZEREQUEST']._serialized_start=344
  _globals['_SYNTHESIZEREQUEST']._serialized_end=471
  _globals['_SPEECHSERVICE']._serialized_start=474
  _globals['_SPEECHSERVICE']._serialized_end=720
# @@protoc_insertion_point(module_scope)
